swagger: "2.0"
info:
  description: |
    This is a sample server Petstore server.

    [Learn about Swagger](http://swagger.io) or join the IRC channel `#swagger` on irc.freenode.net.

    For this sample, you can use the api key `special-key` to test the authorization filters
  version: "1.0.0"
  title: Swagger Petstore
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8080
basePath: /api
produces:
  - application/json
schemes:
  - http
paths:
  /job:
    post:
      operationId: "create_job"
      parameters:
        - in: body
          name: body
          description: Job object 
          required: tue
          schema:
            $ref: "#/definitions/Job"
      responses:
        "405":
          description: Invalid input
  /job/{jobId}:
    put:
      operationId: "update_job"
      parameters:
        - in: path
          name: jobId
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Job"
        "400":
          description: Invalid ID supplied
    get:
      operationId: "get_job"
      parameters:
        - in: path
          name: jobId
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Job"
        "400":
          description: Invalid ID supplied
definitions:
  Job:
    type: object
    required:
      - name
      - id
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: doggie
     