---
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.\n\n[Learn about Swagger](http://swagger.io)\
    \ or join the IRC channel `#swagger` on irc.freenode.net.\n\nFor this sample,\
    \ you can use the api key `special-key` to test the authorization filters\n"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://helloreverb.com/terms/"
  contact:
    name: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8081"
basePath: "/api"
produces:
  - application/json
schemes:
- "http"
paths:
  /job:
    post:
      operationId: "create_job"
      parameters:
      - in: "body"
        name: "body"
        description: "Job object"
        required: false
        schema:
          $ref: "#/definitions/Job"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "jobmanager.WebControllers.default_controller"
  /job/{jobId}:
    get:
      operationId: "get_job"
      parameters:
      - name: "jobId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Invalid ID supplied"
      x-swagger-router-controller: "jobmanager.WebControllers.default_controller"
    put:
      operationId: "update_job"
      parameters:
      - name: "jobId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Invalid ID supplied"
      x-swagger-router-controller: "jobmanager.WebControllers.default_controller"
definitions:
  Job:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
